package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.AgentRolePKDao;
import org.seadva.registry.database.model.obj.vaRegistry.AgentRolePK;
 
/**
 * DAO for table: AgentRolePK.
 * @author autogenerated
 */

public class AgentRolePKDaoImpl implements AgentRolePKDao {
	

	}

