package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.AgentProfilePKDao;
import org.springframework.stereotype.Repository;
 
/**
 * DAO for table: AgentProfilePK.
 * @author autogenerated
 */
@Repository
public class AgentProfilePKDaoImpl implements AgentProfilePKDao {

	}

