package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.apache.log4j.Logger;
import org.seadva.registry.database.common.DBConnectionPool;
import org.seadva.registry.database.common.ObjectPool;
import org.seadva.registry.database.model.dao.vaRegistry.AgentRoleDao;
import org.seadva.registry.database.model.obj.vaRegistry.AgentRole;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * DAO for table: AgentRole.
 * @author autogenerated
 */

public class AgentRoleDaoImpl implements AgentRoleDao {
    private static Logger log = Logger.getLogger(AgentRoleDaoImpl.class);

    protected Connection getConnection() throws SQLException {
        return connectionPool.getEntry();
    }
    public AgentRoleDaoImpl(){
        connectionPool = DBConnectionPool.getInstance();
    }


    protected ObjectPool<Connection> connectionPool = null;

    @Override
    public boolean putAgentRole(AgentRole agentRole, String agentId) {
        Connection connection = null;
        PreparedStatement statement = null;
        try {
            connection = getConnection();

            statement = connection.prepareStatement("INSERT INTO agent_role values(?,?)");
            statement.setString(1, agentId);
            statement.setString(2, agentRole.getId().getRoleType().getId());
            statement.executeUpdate();
            statement.close();
            log.debug("Done resetting unfinished raw notifications");
        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }

        return true;
    }
}

