package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.AggregationPKDao;
import org.springframework.stereotype.Repository;
 
/**
 * DAO for table: AggregationPK.
 * @author autogenerated
 */
@Repository
public class AggregationPKDaoImpl implements AggregationPKDao {

	}

