package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.common.DBConnectionPool;
import org.seadva.registry.database.common.ObjectPool;
import org.seadva.registry.database.model.dao.vaRegistry.DataIdentifierTypeDao;
import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifierType;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 * DAO for table: DataIdentifierType.
 * @author autogenerated
 */

public class DataIdentifierTypeDaoImpl implements DataIdentifierTypeDao {

    protected Connection getConnection() throws SQLException {
        return connectionPool.getEntry();
    }

    public DataIdentifierTypeDaoImpl(){
        connectionPool = DBConnectionPool.getInstance();
    }


    protected ObjectPool<Connection> connectionPool = null;

    @Override
    public DataIdentifierType getDataIdentifierType(String dataIdentifierTypeName) {
        DataIdentifierType dataIdentifierType = new DataIdentifierType();
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();

            statement = connection.prepareStatement("Select * from data_identifier_type where data_identifier_type_name=?");
            statement.setString(1, dataIdentifierTypeName);
            ResultSet resultSet = statement.executeQuery();


            while (resultSet.next()) {
                dataIdentifierType.setId(resultSet.getString("data_identifier_type_id"));
                dataIdentifierType.setDataIdentifierTypeName(resultSet.getString("data_identifier_type_name"));
                dataIdentifierType.setSchemaUri(resultSet.getString("schema_uri"));
                break;
            }

        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    //  log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }
        return dataIdentifierType;
    }

    @Override
    public DataIdentifierType getDataIdentifierTypeById(String dataIdentifierTypeId) {
        DataIdentifierType dataIdentifierType = new DataIdentifierType();
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();

            statement = connection.prepareStatement("Select * from data_identifier_type where data_identifier_type_id=?");
            statement.setString(1, dataIdentifierTypeId);
            ResultSet resultSet = statement.executeQuery();


            while (resultSet.next()) {
                dataIdentifierType.setId(resultSet.getString("data_identifier_type_id"));
                dataIdentifierType.setDataIdentifierTypeName(resultSet.getString("data_identifier_type_name"));
                dataIdentifierType.setSchemaUri(resultSet.getString("schema_uri"));
                break;
            }

        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    //  log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }
        return dataIdentifierType;
    }
}

