package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.DataLocationPKDao;
 
/**
 * DAO for table: DataLocationPK.
 * @author autogenerated
 */

public class DataLocationPKDaoImpl implements DataLocationPKDao {
	

	}

