package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.DataIdentifierPKDao;
 
/**
 * DAO for table: DataIdentifierPK.
 * @author autogenerated
 */

public class DataIdentifierPKDaoImpl  implements DataIdentifierPKDao {

	}

