package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.EntityTypePKDao;
 
/**
 * DAO for table: EntityTypePK.
 * @author autogenerated
 */

public class EntityTypePKDaoImpl implements EntityTypePKDao {

	}

