package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.EntityTypeDao;
 
/**
 * DAO for table: EntityType.
 * @author autogenerated
 */

public class EntityTypeDaoImpl implements EntityTypeDao {

	}

