package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.EntityContentDao;
 
 
/**
 * DAO for table: EntityContent.
 * @author autogenerated
 */

public class EntityContentDaoImpl implements EntityContentDao {
	

	}

