package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.EventDao;
 
 
/**
 * DAO for table: Event.
 * @author autogenerated
 */

public class EventDaoImpl implements EventDao {

	}

