package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.EventTypeDao;
 
 
/**
 * DAO for table: EventType.
 * @author autogenerated
 */

public class EventTypeDaoImpl implements EventTypeDao {

	}

