package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.FixityPKDao;
 
/**
 * DAO for table: FixityPK.
 * @author autogenerated
 */

public class FixityPKDaoImpl implements FixityPKDao {

}

