package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.FormatDao;
 
 
/**
 * DAO for table: Format.
 * @author autogenerated
 */

public class FormatDaoImpl implements FormatDao {

	}

