package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.MetadataReferenceDao;
 
 
/**
 * DAO for table: MetadataReference.
 * @author autogenerated
 */

public class MetadataReferenceDaoImpl implements MetadataReferenceDao {

	}

