package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.RelationPKDao;
 
/**
 * DAO for table: RelationPK.
 * @author autogenerated
 */

public class RelationPKDaoImpl implements RelationPKDao {

	}

