package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.common.DBConnectionPool;
import org.seadva.registry.database.common.ObjectPool;
import org.seadva.registry.database.model.dao.vaRegistry.RoleTypeDao;
import org.seadva.registry.database.model.obj.vaRegistry.RoleType;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 * DAO for table: RoleType.
 * @author autogenerated
 */
public class RoleTypeDaoImpl implements RoleTypeDao {
    protected Connection getConnection() throws SQLException {
        return connectionPool.getEntry();
    }
    public RoleTypeDaoImpl(){
        connectionPool = DBConnectionPool.getInstance();
    }


    protected ObjectPool<Connection> connectionPool = null;
    @Override
    public RoleType getRoleType(String roleName) {
        RoleType roleType = new RoleType();
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();

            statement = connection.prepareStatement("Select * from role_type where role_type_name=?");
            statement.setString(1, roleName);
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                roleType.setId(resultSet.getString("role_type_id"));
                roleType.setRoleTypeName(resultSet.getString("role_type_name"));
                roleType.setRoleDescription(resultSet.getString("role_description"));
                break;
            }


        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    //  log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }
        return roleType;
    }
}

