package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.common.DBConnectionPool;
import org.seadva.registry.database.common.ObjectPool;
import org.seadva.registry.database.model.dao.vaRegistry.StateDao;
import org.seadva.registry.database.model.obj.vaRegistry.State;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 * DAO for table: State.
 * @author autogenerated
 */

public class StateDaoImpl implements StateDao {

    protected Connection getConnection() throws SQLException {
        return connectionPool.getEntry();
    }
    public StateDaoImpl(){
        connectionPool = DBConnectionPool.getInstance();
    }
    protected ObjectPool<Connection> connectionPool = null;

    @Override
    public State getState(String stateName) {
        State state = new State();
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();

            statement = connection.prepareStatement("Select * from state where state_type=?");
            statement.setString(1, stateName);
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                state.setId(resultSet.getString("state_id"));
                state.setStateName(resultSet.getString("state_name"));
                state.setStateType(resultSet.getString("state_type"));
                break;
            }


        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    //  log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }
        return state;
    }

    @Override
    public State getStateById(String stateId) {
        State state = new State();
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();

            statement = connection.prepareStatement("Select * from state where state_id=?");
            statement.setString(1, stateId);
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                state.setId(resultSet.getString("state_id"));
                state.setStateName(resultSet.getString("state_name"));
                state.setStateType(resultSet.getString("state_type"));
                break;
            }


        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    //  log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }
        return state;
    }
}

