package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.TransitionDao;
 
/**
 * DAO for table: Transition.
 * @author autogenerated
 */

public class TransitionDaoImpl implements TransitionDao {

	}

