package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.seadva.registry.database.model.dao.vaRegistry.TransitionPKDao;
 
/**
 * DAO for table: TransitionPK.
 * @author autogenerated
 */

public class TransitionPKDaoImpl implements TransitionPKDao {
	

	}

