package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.AgentRole;

/**
 * DAO interface for table: AgentRole.
 * @author autogenerated
 */
public interface AgentRoleDao {
	boolean putAgentRole(AgentRole agentRole, String agentId);
}

