package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.AgentProfile;

/**
 * DAO interface for table: AgentProfile.
 * @author autogenerated
 */
public interface AgentProfileDao {
    boolean putAgentProfile(AgentProfile agentProfile, String agentId);
}

