package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.Agent;

/**
 * DAO interface for table: Agent.
 * @author autogenerated
 */
public interface AgentDao {
	boolean putAgent(Agent agent);
}

