package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.BaseEntity;
 
/**
 * DAO interface for table: BaseEntity.
 * @author autogenerated
 */
public interface BaseEntityDao {
	// constructor only
    BaseEntity getBaseEntity(String entityId);
    boolean updateEntity(String entityId, int isObsolete);
    boolean insertEntity(BaseEntity baseEntity);
}

