package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.Collection;

import java.util.List;

/**
 * DAO interface for table: Collection.
 * @author autogenerated
 */
public interface CollectionDao {

    Collection getCollection(String entityId);
    boolean insertCollection(Collection collection);
    List<Collection> listCollections(String submitterId, String repository, String type);
    public List<Collection> queryByProperty(String key, String value);
}

