package org.seadva.registry.database.model.dao.vaRegistry;

/**
 * DAO interface for table: DataIdentifierPK.
 * @author autogenerated
 */
public interface DataIdentifierPKDao {
	// constructor only
}

