package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifier;
import org.seadva.registry.database.model.obj.vaRegistry.DataLocation;

import java.util.List;
import java.util.Set;

/**
 * DAO interface for table: DataLocation.
 * @author autogenerated
 */
public interface DataLocationDao {
    List<DataLocation> getDataLocations(String entityId);
    boolean putDataLocations(String entityId, Set<DataLocation> dataLocationSet);
}

