package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifier;

import java.util.List;
import java.util.Set;

/**
 * DAO interface for table: DataIdentifier.
 * @author autogenerated
 */
public interface DataIdentifierDao  {
    List<DataIdentifier> getDataIdentifiers(String entityId);
    boolean putDataIdentifiers(String entityId, Set<DataIdentifier> dataIdentifierSet);

    List<DataIdentifier> getDataIdentifiersByValue(String alternateId);
}

