package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifierType;

/**
 * DAO interface for table: DataIdentifierType.
 * @author autogenerated
 */
public interface DataIdentifierTypeDao {
	// constructor only
    DataIdentifierType getDataIdentifierType(String idTypeName);
    DataIdentifierType getDataIdentifierTypeById(String typeId);
}

