package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.File;

/**
 * DAO interface for table: File.
 * @author autogenerated
 */
public interface FileDao {
    File getFile(String entityId);
    boolean insertFile(File file);
}

