package org.seadva.registry.database.model.dao.vaRegistry;

/**
 * DAO interface for table: MetadataReference.
 * @author autogenerated
 */
public interface MetadataReferenceDao {
	// constructor only
}

