package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.ProfileType;

/**
 * DAO interface for table: ProfileType.
 * @author autogenerated
 */
public interface ProfileTypeDao {
	// constructor only
    public ProfileType getProfileType(String element);
}

