package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.Property;

import java.util.List;
import java.util.Set;

/**
 * DAO interface for table: Property.
 * @author autogenerated
 */
public interface PropertyDao {
	// constructor only
    List<Property> getProperties(String entityId);
    boolean putProperties(String entityId, Set<Property> properties);
    boolean deleteProperties(String entityId);
}

