package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.Relation;

import java.util.List;

/**
 * DAO interface for table: Relation.
 * @author autogenerated
 */
public interface RelationDao {
    List<Relation> getRelations(String causeId);
    boolean putRelation(Relation relation);
    boolean deleteRelation(Relation relation);
}

