package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.RelationType;

/**
 * DAO interface for table: RelationType.
 * @author autogenerated
 */
public interface RelationTypeDao {
	// constructor only
    RelationType getRelationTypeByName(String relationName);
    RelationType getRelationTypeById(String relationTypeId);
}

