package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.RoleType;

/**
 * DAO interface for table: RoleType.
 * @author autogenerated
 */
public interface RoleTypeDao {
	// constructor only
    RoleType getRoleType(String roleName);
}

