package org.seadva.registry.database.model.dao.vaRegistry;

import org.seadva.registry.database.model.obj.vaRegistry.State;

/**
 * DAO interface for table: State.
 * @author autogenerated
 */
public interface StateDao{
	// constructor only
    State getState(String stateName);
    State getStateById(String stateId);
}

