package org.seadva.registry.database.enums.subtype.vaRegistry;
/**
 * Defines the BaseEntitySubclassType enumeration.
 * 
 * @author autogenerated
 *
 */
public enum BaseEntitySubclassType {

	/** Enum Constant. */
	AGENT,
	/** Enum Constant. */
	NOT_A_CHILD,
	/** Enum Constant. */
	COLLECTION,
	/** Enum Constant. */
	EVENT,
	/** Enum Constant. */
	FILE,
	/** Enum Constant. */
	STATE;

}
